# ILC level 2 centroids + smart features KMeans

Этот ноутбук кластеризует статьи по `smart_features`, используя узлы ILC второго уровня как фиксированные центроиды для KMeans.

Логика:

1. загрузить статьи с NER/keywords;
2. собрать `smart_features = keywords + meaningful NER`;
3. взять узлы ILC на глубине 2;
4. построить embeddings статей и ILC-центроидов одной моделью;
5. запустить KMeans с `init=ilc_level2_centroids`, `n_init=1`, `max_iter=1`;
6. сохранить статьи с `ilc_level2_cluster`, `ilc_notation`, `ilc_label`, `min_distance_to_ilc_center`.

In [9]:
USE_DIM_REDUCTION = True
DIM_REDUCTION_DIM = 10

In [10]:
from pathlib import Path
import json
import numpy as np
import pandas as pd
from tqdm import tqdm
import re
from collections import Counter
import matplotlib.pyplot as plt
from wordcloud import WordCloud

from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import calinski_harabasz_score, davies_bouldin_score, pairwise_distances, silhouette_score
from sklearn.preprocessing import StandardScaler

In [22]:
# Configuration paths and constants
DATA_DIR = Path("../data")
ARTIFACTS = DATA_DIR / "artifacts"
ARTIFACTS.mkdir(parents=True, exist_ok=True)

ARTICLES_CSV = ARTIFACTS / "articles_with_ilc_classes.csv"
SMART_ARTICLES_CSV = ARTIFACTS / "articles_with_smart_features.csv"
WITH_ORCID_CSV = Path("../misc/orcid_profiles_with_ner.csv")
SMART_WITH_ORCID_CSV = ARTIFACTS / "smart_with_orcid.csv"
OUTPUT_CSV = ARTIFACTS / "articles_with_ilc_level2_kmeans.csv"
WITH_ORCID_LEVEL2_CSV = ARTIFACTS / "with_orcid_level2_assignments.csv"

ILC_JSON = Path("../parse/ilc_tree_depth3.json")
ILC_LEVEL2_METADATA_PATH = ARTIFACTS / "ilc_level2_centroids.pkl"

CLUSTERING_QUALITY_CSV = ARTIFACTS / "ilc_level2_clustering_quality.csv"
PCA_CLUSTERING_QUALITY_CSV = ARTIFACTS / "pca_clustering_quality.csv"
AUTHOR_TOPK_CSV = ARTIFACTS / "author_topk_ilc_centroids.csv"
AUTHOR_WORKS_SUMMARY_CSV = ARTIFACTS / "author_works_summary.csv"

ARTICLE_EMBEDDINGS_PATH = ARTIFACTS / "article_embeddings.npy"
ILC_LEVEL2_CENTROIDS_PATH = ARTIFACTS / "ilc_level2_centroids.npy"
AUTHOR_EMBEDDINGS_PATH = ARTIFACTS / "author_embeddings.npy"
WITH_ORCID_EMBEDDINGS_PATH = ARTIFACTS / "with_orcid_embeddings.npy"

MODEL_NAME = "sentence-transformers/all-mpnet-base-v2"
BATCH_SIZE = 32
TOP_K_CENTROIDS = 5
QUALITY_SAMPLE_SIZE = 10000

print("Configuration initialized.")
print(f"Data directory: {DATA_DIR}")
print(f"Artifacts directory: {ARTIFACTS}")

Configuration initialized.
Data directory: ..\data
Artifacts directory: ..\data\artifacts

## Загрузка статей и сбор smart features

In [12]:
MEANINGLESS_NER_CATEGORIES = {"DATE", "TIME", "PERCENT", "MONEY", "QUANTITY", "CARDINAL", "ORDINAL"}

def parse_keywords(value):
    if pd.isna(value) or not isinstance(value, str):
        return []
    words = []
    for item in value.split("; "):
        try:
            keyword, _ = item.split("|")
            keyword = keyword.strip()
            if keyword:
                words.append(keyword)
        except ValueError:
            continue
    return words

def parse_ner(value):
    if pd.isna(value) or not isinstance(value, str):
        return []
    words = []
    for item in value.split("; "):
        try:
            word, label, _ = item.split("|")
            word = word.strip()
            if word and label not in MEANINGLESS_NER_CATEGORIES:
                words.append(word)
        except ValueError:
            continue
    return words

def combine_smart_features(row):
    return " ".join(parse_keywords(row.get("keywords")) + parse_ner(row.get("ner_entities")))

df_articles = pd.read_csv(ARTICLES_CSV)
print("Статей:", len(df_articles))

if "smart_features" not in df_articles.columns:
    tqdm.pandas(desc="smart_features")
    df_articles["smart_features"] = df_articles.progress_apply(combine_smart_features, axis=1)

df_articles.to_csv(SMART_ARTICLES_CSV, index=False)
print("Сохранено:", SMART_ARTICLES_CSV)
df_articles[["oai_identifier", "smart_features"]].head()

Статей: 124282

smart_features: 100%|██████████| 124282/124282 [00:01<00:00, 89766.01it/s]

Сохранено: ..\data\artifacts\articles_with_smart_features.csv

,oai_identifier,smart_features
0,oai:dspace.mit.edu:1721.1/126771,computing 1980s finance visicalc pioneering ma...
1,oai:dspace.mit.edu:1721.1/161710,2008 dean student report president year studen...
2,oai:dspace.mit.edu:1721.1/11248,anisotropy dimensional printing structural cer...
3,oai:dspace.mit.edu:1721.1/3029,parallel processing communication aspects supp...
4,oai:dspace.mit.edu:1721.1/8302,dna electrophoresis microdevices filled polyme...

## ILC level 2: сбор центроидов

In [13]:
with open(ILC_JSON, "r", encoding="utf-8") as f:
    ilc_tree = json.load(f)

def collect_nodes_at_depth(node, current_depth=1, target_depth=2):
    if current_depth == target_depth:
        return [node]
    if current_depth > target_depth:
        return []
    nodes = []
    for child in node.get("children", []):
        nodes.extend(collect_nodes_at_depth(child, current_depth + 1, target_depth))
    return nodes

level2_nodes = []
for root in ilc_tree:
    level2_nodes.extend(collect_nodes_at_depth(root, current_depth=1, target_depth=2))

def build_ilc_text(node):
    parts = [node.get("description", ""), node.get("label", "")]
    return " ".join(str(part).strip() for part in parts if str(part).strip())

df_centroids = pd.DataFrame([
    {
        "notation": node.get("notation"),
        "label": node.get("label"),
        "combined_text": build_ilc_text(node),
    }
    for node in level2_nodes
])

df_centroids.to_pickle(ILC_LEVEL2_METADATA_PATH)
print("ILC level 2 центроидов:", len(df_centroids))
print("Сохранено:", ILC_LEVEL2_METADATA_PATH)
df_centroids.head()

ILC level 2 центроидов: 333
Сохранено: ..\data\artifacts\ilc_level2_centroids.pkl

  notation                        label                combined_text
0       UX  persons by birth millennium  persons by birth millennium
1       XA                           x0                           x0
2       XB                           x1                           x1
3       XC                           x2                           x2
4       XX                         what                         what

## Векторизация smart features и ILC level 2 центроидов

In [14]:
def encode_texts(texts, model, batch_size=32, desc="embeddings"):
    embeddings = []
    for start in tqdm(range(0, len(texts), batch_size), desc=desc):
        batch = texts[start:start + batch_size]
        embeddings.extend(model.encode(batch, show_progress_bar=False))
    return np.asarray(embeddings, dtype="float32")

model = SentenceTransformer(MODEL_NAME)

if ARTICLE_EMBEDDINGS_PATH.exists():
    article_embeddings = np.load(ARTICLE_EMBEDDINGS_PATH)
    if article_embeddings.shape[0] != len(df_articles):
        print("Размер старых embeddings не совпадает с числом статей, пересчитываю...")
        article_embeddings = encode_texts(df_articles["smart_features"].fillna("").astype(str).tolist(), model, BATCH_SIZE, "article embeddings")
        np.save(ARTICLE_EMBEDDINGS_PATH, article_embeddings)
else:
    article_embeddings = encode_texts(df_articles["smart_features"].fillna("").astype(str).tolist(), model, BATCH_SIZE, "article embeddings")
    np.save(ARTICLE_EMBEDDINGS_PATH, article_embeddings)

if ILC_LEVEL2_CENTROIDS_PATH.exists():
    ilc_centroids = np.load(ILC_LEVEL2_CENTROIDS_PATH)
    if ilc_centroids.shape[0] != len(df_centroids):
        print("Размер старых ILC embeddings не совпадает с числом центроидов, пересчитываю...")
        ilc_centroids = encode_texts(df_centroids["combined_text"].fillna("").astype(str).tolist(), model, BATCH_SIZE, "ILC level 2 centroids")
        np.save(ILC_LEVEL2_CENTROIDS_PATH, ilc_centroids)
else:
    ilc_centroids = encode_texts(df_centroids["combined_text"].fillna("").astype(str).tolist(), model, BATCH_SIZE, "ILC level 2 centroids")
    np.save(ILC_LEVEL2_CENTROIDS_PATH, ilc_centroids)

print("article_embeddings:", article_embeddings.shape)
print("ilc_centroids:", ilc_centroids.shape)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4774.16it/s]
MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
article embeddings: 100%|██████████| 3884/3884 [27:37<00:00,  2.34it/s]

Размер старых ILC embeddings не совпадает с числом центроидов, пересчитываю...

ILC level 2 centroids: 100%|██████████| 11/11 [00:00<00:00, 19.68it/s]

article_embeddings: (124282, 768)
ilc_centroids: (333, 768)

## Dimensionality reduction with PCA

Apply PCA to the normalized article embeddings and ILC centroids before clustering. This reduces the embedding dimensionality and allows evaluating how much structure is preserved.

In [16]:
if USE_DIM_REDUCTION:
    scaler_pca = StandardScaler()
    article_embeddings_scaled_for_pca = scaler_pca.fit_transform(article_embeddings)
    ilc_centroids_scaled_for_pca = scaler_pca.transform(ilc_centroids)

    pca = PCA(n_components=min(DIM_REDUCTION_DIM, article_embeddings_scaled_for_pca.shape[1]), random_state=42)
    article_embeddings_reduced = pca.fit_transform(article_embeddings_scaled_for_pca)
    ilc_centroids_reduced = pca.transform(ilc_centroids_scaled_for_pca)
    print(f"PCA components: {article_embeddings_reduced.shape[1]}")
    print(f"Explained variance ratio sum: {pca.explained_variance_ratio_.sum():.4f}")
else:
    article_embeddings_reduced = article_embeddings
    ilc_centroids_reduced = ilc_centroids
    print(f"Dimensionality reduction disabled, using original embedding dimension: {article_embeddings_reduced.shape[1]}")

np.save(ARTIFACTS / "article_embeddings_pca.npy", article_embeddings_reduced)
np.save(ARTIFACTS / "ilc_level2_centroids_pca.npy", ilc_centroids_reduced)

kmeans_pca = KMeans(
    n_clusters=len(ilc_centroids_reduced),
    init="k-means++",
    n_init=10,
    max_iter=300,
    random_state=42,
)

pca_labels = kmeans_pca.fit_predict(article_embeddings_reduced)
pca_distances = pairwise_distances(article_embeddings_reduced, kmeans_pca.cluster_centers_, metric="cosine")

# Calculate nearest original ILC centroid for comparison
pca_distances_to_original = pairwise_distances(article_embeddings_reduced, ilc_centroids_reduced, metric="cosine")
nearest_original_centroid = pca_distances_to_original.argmin(axis=1)

pca_quality = {
    "n_articles": int(len(pca_labels)),
    "n_centroids": int(len(kmeans_pca.cluster_centers_)),
    "n_used_clusters": int(len(np.unique(pca_labels))),
    "n_empty_clusters": int(len(kmeans_pca.cluster_centers_) - len(np.unique(pca_labels))),
    "mean_assigned_cosine_distance": float(np.mean(pca_distances.min(axis=1))),
    "median_assigned_cosine_distance": float(np.median(pca_distances.min(axis=1))),
    "p95_assigned_cosine_distance": float(np.percentile(pca_distances.min(axis=1), 95)),
    "kmeans_matches_nearest_original_centroid_ratio": float(np.mean(pca_labels == nearest_original_centroid)),
}

metric_embeddings_pca = article_embeddings_reduced
metric_labels_pca = pca_labels
if len(metric_labels_pca) > QUALITY_SAMPLE_SIZE:
    rng = np.random.default_rng(42)
    sample_idx = rng.choice(len(metric_labels_pca), size=QUALITY_SAMPLE_SIZE, replace=False)
    metric_embeddings_pca = metric_embeddings_pca[sample_idx]
    metric_labels_pca = metric_labels_pca[sample_idx]

pca_quality["quality_sample_size"] = int(len(metric_labels_pca))
metric_unique_labels_pca = np.unique(metric_labels_pca)
if 1 < len(metric_unique_labels_pca) < len(metric_labels_pca):
    pca_quality["silhouette_cosine"] = float(silhouette_score(metric_embeddings_pca, metric_labels_pca, metric="cosine"))
    pca_quality["davies_bouldin"] = float(davies_bouldin_score(metric_embeddings_pca, metric_labels_pca))
    pca_quality["calinski_harabasz"] = float(calinski_harabasz_score(metric_embeddings_pca, metric_labels_pca))
else:
    pca_quality["silhouette_cosine"] = np.nan
    pca_quality["davies_bouldin"] = np.nan
    pca_quality["calinski_harabasz"] = np.nan

pca_quality_df = pd.DataFrame([pca_quality])

pca_quality_df.to_csv(PCA_CLUSTERING_QUALITY_CSV, index=False)

print("PCA KMeans quality saved:", PCA_CLUSTERING_QUALITY_CSV)
pca_quality_df

PCA components: 10
Explained variance ratio sum: 0.2670
PCA KMeans quality saved: ..\data\artifacts\pca_clustering_quality.csv

,n_articles,n_centroids,n_used_clusters,n_empty_clusters,mean_assigned_cosine_distance,median_assigned_cosine_distance,p95_assigned_cosine_distance,kmeans_matches_nearest_original_centroid_ratio,quality_sample_size,silhouette_cosine,davies_bouldin,calinski_harabasz
0,124282,333,333,0,0.0839,0.072596,0.187199,0.001786,10000,0.11883,1.759396,159.069019

## KMeans с ILC level 2 центроидами

In [17]:
assert article_embeddings_reduced.shape[0] == len(df_articles), "Число embeddings статей не совпадает с числом строк CSV"
assert article_embeddings_reduced.shape[1] == ilc_centroids_reduced.shape[1], "Размерность article и ILC embeddings различается"

kmeans = KMeans(
    n_clusters=len(ilc_centroids_reduced),
    init=ilc_centroids_reduced,
    n_init=1,
    max_iter=1,
    random_state=42,
)

labels = kmeans.fit_predict(article_embeddings_reduced)
distances = pairwise_distances(article_embeddings_reduced, ilc_centroids_reduced, metric="cosine")

df_result = df_articles.copy()
df_result["ilc_level2_cluster"] = labels
df_result["min_distance_to_ilc_center"] = distances.min(axis=1)
df_result["ilc_notation"] = df_result["ilc_level2_cluster"].map(lambda i: df_centroids.iloc[int(i)]["notation"])
df_result["ilc_label"] = df_result["ilc_level2_cluster"].map(lambda i: df_centroids.iloc[int(i)]["label"])

df_result.to_csv(OUTPUT_CSV, index=False)
print("Сохранено:", OUTPUT_CSV)
df_result[["oai_identifier", "ilc_level2_cluster", "ilc_notation", "ilc_label", "min_distance_to_ilc_center"]].head()

Сохранено: ..\data\artifacts\articles_with_ilc_level2_kmeans.csv

,oai_identifier,ilc_level2_cluster,ilc_notation,ilc_label,min_distance_to_ilc_center
0,oai:dspace.mit.edu:1721.1/126771,15,ag,operations,0.056363
1,oai:dspace.mit.edu:1721.1/161710,5,ZA,the aforementioned,0.079504
2,oai:dspace.mit.edu:1721.1/11248,94,gs,solids,0.204206
3,oai:dspace.mit.edu:1721.1/3029,24,at,algorithms,0.267054
4,oai:dspace.mit.edu:1721.1/8302,35,cd,membranes,0.420779

## Быстрая сводка по кластерам

In [18]:
summary = (
    df_result.groupby(["ilc_notation", "ilc_label"])
    .size()
    .reset_index(name="articles_count")
    .sort_values("articles_count", ascending=False)
)

SUMMARY_CSV = ARTIFACTS / "articles_with_ilc_level2_summary.csv"
summary.to_csv(SUMMARY_CSV, index=False)
print("Сводка сохранена:", SUMMARY_CSV)
summary.head(20)

Сводка сохранена: ..\data\artifacts\articles_with_ilc_level2_summary.csv

    ilc_notation                      ilc_label  articles_count
77            fp                         lipids            2415
81            fx          solid state compounds            2288
280           vt                  manufacturing            2277
299           ww                    settlements            2268
208           qw  language transmission systems            2222
24            at                     algorithms            2122
261           uo                   corporations            2039
296           ws                      buildings            1996
94            gs                         solids            1911
87          ggWl                         fluids            1895
96            gy      Bose-Einstein condensates            1802
146           ki                       plasmids            1782
288           wh                 cleaning tools            1775
35            cd                      membranes            1548
260           ul    limited liability companies            1531
136           jr                       glaciers            1494
84            ge             quark-gluon plasma            1489
177           oc          autonomous activities            1380
59            fc                  mineral acids            1326
99            hb                        nebulae            1317

## Clustering quality for current ILC level 2 centroids

Metrics are computed for article embeddings assigned to ILC level 2 centroids. The block also checks how often KMeans labels match the nearest original ILC centroid by cosine distance.

In [20]:
unique_labels = np.unique(labels)
assigned_distances = distances[np.arange(len(labels)), labels]
nearest_original_centroid = distances.argmin(axis=1)

quality = {
    "n_articles": int(len(labels)),
    "n_centroids": int(len(ilc_centroids_reduced)),
    "n_used_clusters": int(len(unique_labels)),
    "n_empty_clusters": int(len(ilc_centroids_reduced) - len(unique_labels)),
    "mean_assigned_cosine_distance": float(np.mean(assigned_distances)),
    "median_assigned_cosine_distance": float(np.median(assigned_distances)),
    "p95_assigned_cosine_distance": float(np.percentile(assigned_distances, 95)),
    "kmeans_matches_nearest_original_centroid_ratio": float(np.mean(labels == nearest_original_centroid)),
}

metric_embeddings = article_embeddings_reduced
metric_labels = labels
if len(metric_labels) > QUALITY_SAMPLE_SIZE:
    rng = np.random.default_rng(42)
    sample_idx = rng.choice(len(metric_labels), size=QUALITY_SAMPLE_SIZE, replace=False)
    metric_embeddings = metric_embeddings[sample_idx]
    metric_labels = metric_labels[sample_idx]

quality["quality_sample_size"] = int(len(metric_labels))
metric_unique_labels = np.unique(metric_labels)
if 1 < len(metric_unique_labels) < len(metric_labels):
    quality["silhouette_cosine"] = float(silhouette_score(metric_embeddings, metric_labels, metric="cosine"))
    quality["davies_bouldin"] = float(davies_bouldin_score(metric_embeddings, metric_labels))
    quality["calinski_harabasz"] = float(calinski_harabasz_score(metric_embeddings, metric_labels))
else:
    quality["silhouette_cosine"] = np.nan
    quality["davies_bouldin"] = np.nan
    quality["calinski_harabasz"] = np.nan

quality_df = pd.DataFrame([quality])
quality_df.to_csv(CLUSTERING_QUALITY_CSV, index=False)
print("Quality saved:", CLUSTERING_QUALITY_CSV)
quality_df

Quality saved: ..\data\artifacts\ilc_level2_clustering_quality.csv

,n_articles,n_centroids,n_used_clusters,n_empty_clusters,mean_assigned_cosine_distance,median_assigned_cosine_distance,p95_assigned_cosine_distance,kmeans_matches_nearest_original_centroid_ratio,quality_sample_size,silhouette_cosine,davies_bouldin,calinski_harabasz
0,124282,333,333,0,0.272159,0.230579,0.612932,0.521789,10000,0.052949,1.836095,115.364325

## Authors with ORCID: load articles and build smart features

This block selects only records with `orcid`, then uses the same `smart_features` logic: keywords plus meaningful NER entities.

In [24]:
df_with_orcid = pd.read_csv(WITH_ORCID_CSV)
df_with_orcid = df_with_orcid.dropna(subset=["orcid"]).copy()
df_with_orcid["orcid"] = df_with_orcid["orcid"].astype(str)

if "smart_features" not in df_with_orcid.columns:
    tqdm.pandas(desc="author article smart_features")
    df_with_orcid["smart_features"] = df_with_orcid.progress_apply(combine_smart_features, axis=1)

df_with_orcid.to_csv(SMART_WITH_ORCID_CSV, index=False)
print("Articles with ORCID:", len(df_with_orcid))
print("Unique ORCID:", df_with_orcid["orcid"].nunique())
print("Saved:", SMART_WITH_ORCID_CSV)
print("Available columns:", df_with_orcid.columns.tolist())
df_with_orcid.head()

author article smart_features: 100%|██████████| 5770/5770 [00:00<00:00, 40061.20it/s]

Articles with ORCID: 5770
Unique ORCID: 5770
Saved: ..\data\artifacts\smart_with_orcid.csv
Available columns: ['orcid', 'title', 'description', 'entities', 'smart_features']

,orcid,title,description,entities,smart_features
0,http://orcid.org/0000-0001-5821-1562,Optimizing the Supply Chain Design for Sourcin...,A significant supply disruption occurred in 20...,AZ; AstraZeneca; B,
1,http://orcid.org/0000-0001-6681-5710,Understanding and Reshaping Social Networks wi...,Social networks are powerful in modeling inter...,NaN,
2,http://orcid.org/0000-0001-8849-4268,Urban Planning and Religious Practice: Three C...,Religion in urban planning is conventionally v...,Western; non-Western; Iraq; Albania; Protestan...,
3,http://orcid.org/0000-0002-0163-9215,Low Power Adaptive Wireless Circuits for the I...,The emergence of the Internet of Things (IoT) ...,Bluetooth Low Energy; Internet of Things; IoT,
4,http://orcid.org/0000-0002-0421-890X,Probabilistic modeling and Bayesian inference ...,Probabilistic modeling and Bayesian inference ...,ov; Hessian; Bayesian; Mark; Gaussian; non,

## Strategy 1: one vector per author, top-k nearest ILC level 2 centroids

For each ORCID, all article `smart_features` are concatenated into one author profile text. The author vector is compared with ILC level 2 centroids, and the top-k closest centroids are saved.

In [26]:
author_profiles = (
    df_with_orcid.groupby("orcid")
    .agg(
        works_count=("orcid", "count"),
        author_smart_features=("smart_features", lambda values: " ".join(values.fillna("").astype(str))),
    )
    .reset_index()
)

if AUTHOR_EMBEDDINGS_PATH.exists():
    author_embeddings = np.load(AUTHOR_EMBEDDINGS_PATH)
    if author_embeddings.shape[0] != len(author_profiles):
        print("Old author embeddings size mismatch, recomputing...")
        author_embeddings = encode_texts(author_profiles["author_smart_features"].fillna("").astype(str).tolist(), model, BATCH_SIZE, "author embeddings")
        np.save(AUTHOR_EMBEDDINGS_PATH, author_embeddings)
else:
    author_embeddings = encode_texts(author_profiles["author_smart_features"].fillna("").astype(str).tolist(), model, BATCH_SIZE, "author embeddings")
    np.save(AUTHOR_EMBEDDINGS_PATH, author_embeddings)

author_embeddings_scaled_for_pca = scaler_pca.transform(author_embeddings)
author_embeddings_reduced = pca.transform(author_embeddings_scaled_for_pca)
author_distances = pairwise_distances(author_embeddings_reduced, ilc_centroids_reduced, metric="cosine")
topk_indices = np.argsort(author_distances, axis=1)[:, :TOP_K_CENTROIDS]

author_topk_rows = []
for author_idx, row in author_profiles.iterrows():
    top_parts = []
    out = {
        "orcid": row["orcid"],
        "works_count": int(row["works_count"]),
    }
    for rank, centroid_idx in enumerate(topk_indices[author_idx], start=1):
        centroid = df_centroids.iloc[int(centroid_idx)]
        distance = float(author_distances[author_idx, centroid_idx])
        out[f"top{rank}_ilc_notation"] = centroid["notation"]
        out[f"top{rank}_ilc_label"] = centroid["label"]
        out[f"top{rank}_distance"] = distance
        top_parts.append(f"{centroid['notation']}:{centroid['label']}:{distance:.4f}")
    out["topk_centroids"] = "; ".join(top_parts)
    author_topk_rows.append(out)

df_author_topk = pd.DataFrame(author_topk_rows)
df_author_topk.to_csv(AUTHOR_TOPK_CSV, index=False)
print("Author top-k saved:", AUTHOR_TOPK_CSV)
df_author_topk.head()

author embeddings: 100%|██████████| 181/181 [00:03<00:00, 59.09it/s]

Author top-k saved: ..\data\artifacts\author_topk_ilc_centroids.csv

,orcid,works_count,top1_ilc_notation,top1_ilc_label,top1_distance,top2_ilc_notation,top2_ilc_label,top2_distance,top3_ilc_notation,top3_ilc_label,top3_distance,top4_ilc_notation,top4_ilc_label,top4_distance,top5_ilc_notation,top5_ilc_label,top5_distance,topk_centroids
0,http://orcid.org/0000-0001-5821-1562,1,kf,tRNA,0.093689,mg,rhizaria,0.097119,rwzs,Scientology,0.119508,aWz,world,0.136194,sf,families,0.140926,kf:tRNA:0.0937; mg:rhizaria:0.0971; rwzs:Scien...
1,http://orcid.org/0000-0001-6681-5710,1,kf,tRNA,0.093689,mg,rhizaria,0.097119,rwzs,Scientology,0.119508,aWz,world,0.136194,sf,families,0.140926,kf:tRNA:0.0937; mg:rhizaria:0.0971; rwzs:Scien...
2,http://orcid.org/0000-0001-8849-4268,1,kf,tRNA,0.093689,mg,rhizaria,0.097119,rwzs,Scientology,0.119508,aWz,world,0.136194,sf,families,0.140926,kf:tRNA:0.0937; mg:rhizaria:0.0971; rwzs:Scien...
3,http://orcid.org/0000-0002-0163-9215,1,kf,tRNA,0.093689,mg,rhizaria,0.097119,rwzs,Scientology,0.119508,aWz,world,0.136194,sf,families,0.140926,kf:tRNA:0.0937; mg:rhizaria:0.0971; rwzs:Scien...
4,http://orcid.org/0000-0002-0421-890X,1,kf,tRNA,0.093689,mg,rhizaria,0.097119,rwzs,Scientology,0.119508,aWz,world,0.136194,sf,families,0.140926,kf:tRNA:0.0937; mg:rhizaria:0.0971; rwzs:Scien...

## Strategy 2: article vectors first, then author summaries

Each author's articles are vectorized and assigned to ILC level 2 centroids. Then the notebook builds author-level summaries: primary centroid, number of distinct centroids, average distance, and top centroids by article count.

In [27]:
if WITH_ORCID_EMBEDDINGS_PATH.exists():
    with_orcid_embeddings = np.load(WITH_ORCID_EMBEDDINGS_PATH)
    if with_orcid_embeddings.shape[0] != len(df_with_orcid):
        print("Old with-orcid embeddings size mismatch, recomputing...")
        with_orcid_embeddings = encode_texts(df_with_orcid["smart_features"].fillna("").astype(str).tolist(), model, BATCH_SIZE, "with-orcid article embeddings")
        np.save(WITH_ORCID_EMBEDDINGS_PATH, with_orcid_embeddings)
else:
    with_orcid_embeddings = encode_texts(df_with_orcid["smart_features"].fillna("").astype(str).tolist(), model, BATCH_SIZE, "with-orcid article embeddings")
    np.save(WITH_ORCID_EMBEDDINGS_PATH, with_orcid_embeddings)

with_orcid_embeddings_scaled_for_pca = scaler_pca.transform(with_orcid_embeddings)
with_orcid_embeddings_reduced = pca.transform(with_orcid_embeddings_scaled_for_pca)
with_orcid_distances = pairwise_distances(with_orcid_embeddings_reduced, ilc_centroids_reduced, metric="cosine")
with_orcid_labels = with_orcid_distances.argmin(axis=1)

df_with_orcid_result = df_with_orcid.copy()
df_with_orcid_result["ilc_level2_cluster"] = with_orcid_labels
df_with_orcid_result["min_distance_to_ilc_center"] = with_orcid_distances.min(axis=1)
df_with_orcid_result["ilc_notation"] = df_with_orcid_result["ilc_level2_cluster"].map(lambda i: df_centroids.iloc[int(i)]["notation"])
df_with_orcid_result["ilc_label"] = df_with_orcid_result["ilc_level2_cluster"].map(lambda i: df_centroids.iloc[int(i)]["label"])
df_with_orcid_result.to_csv(WITH_ORCID_LEVEL2_CSV, index=False)
print("With-ORCID article assignments saved:", WITH_ORCID_LEVEL2_CSV)

summary_rows = []
for orcid, group in df_with_orcid_result.groupby("orcid"):
    counts = (
        group.groupby(["ilc_notation", "ilc_label"])
        .size()
        .reset_index(name="works_count")
        .sort_values("works_count", ascending=False)
    )
    primary = counts.iloc[0]
    top_counts = counts.head(TOP_K_CENTROIDS)
    summary_rows.append({
        "orcid": orcid,
        "works_count": int(len(group)),
        "unique_ilc_centroids": int(len(counts)),
        "primary_ilc_notation": primary["ilc_notation"],
        "primary_ilc_label": primary["ilc_label"],
        "primary_works_count": int(primary["works_count"]),
        "mean_distance_to_ilc_center": float(group["min_distance_to_ilc_center"].mean()),
        "median_distance_to_ilc_center": float(group["min_distance_to_ilc_center"].median()),
        "top_centroids_by_works": "; ".join(
            f"{r.ilc_notation}:{r.ilc_label}:{int(r.works_count)}" for r in top_counts.itertuples(index=False)
        ),
    })

df_author_works_summary = pd.DataFrame(summary_rows).sort_values("works_count", ascending=False)
df_author_works_summary.to_csv(AUTHOR_WORKS_SUMMARY_CSV, index=False)
print("Author works summary saved:", AUTHOR_WORKS_SUMMARY_CSV)
df_author_works_summary.head()

with-orcid article embeddings: 100%|██████████| 181/181 [00:02<00:00, 74.39it/s]

With-ORCID article assignments saved: ..\data\artifacts\with_orcid_level2_assignments.csv
Author works summary saved: ..\data\artifacts\author_works_summary.csv

,orcid,works_count,unique_ilc_centroids,primary_ilc_notation,primary_ilc_label,primary_works_count,mean_distance_to_ilc_center,median_distance_to_ilc_center,top_centroids_by_works
0,http://orcid.org/0000-0001-5821-1562,1,1,kf,tRNA,1,0.093689,0.093689,kf:tRNA:1
1,http://orcid.org/0000-0001-6681-5710,1,1,kf,tRNA,1,0.093689,0.093689,kf:tRNA:1
2,http://orcid.org/0000-0001-8849-4268,1,1,kf,tRNA,1,0.093689,0.093689,kf:tRNA:1
3,http://orcid.org/0000-0002-0163-9215,1,1,kf,tRNA,1,0.093689,0.093689,kf:tRNA:1
4,http://orcid.org/0000-0002-0421-890X,1,1,kf,tRNA,1,0.093689,0.093689,kf:tRNA:1

## Baseline: Standard KMeans without fixed centroids

Run standard KMeans with the same number of clusters (n_clusters = number of ILC level 2 centroids) but without initialization from ILC centroids. This allows comparison of clustering quality with and without domain knowledge.

In [28]:
kmeans_baseline = KMeans(
    n_clusters=len(ilc_centroids_reduced),
    init="k-means++",
    n_init=10,
    max_iter=300,
    random_state=42,
)

baseline_labels = kmeans_baseline.fit_predict(article_embeddings_reduced)
baseline_distances = pairwise_distances(article_embeddings_reduced, kmeans_baseline.cluster_centers_, metric="cosine")

baseline_quality = {
    "n_articles": int(len(baseline_labels)),
    "n_centroids": int(len(kmeans_baseline.cluster_centers_)),
    "n_used_clusters": int(len(np.unique(baseline_labels))),
    "n_empty_clusters": int(len(kmeans_baseline.cluster_centers_) - len(np.unique(baseline_labels))),
    "mean_assigned_cosine_distance": float(np.mean(baseline_distances.min(axis=1))),
    "median_assigned_cosine_distance": float(np.median(baseline_distances.min(axis=1))),
    "p95_assigned_cosine_distance": float(np.percentile(baseline_distances.min(axis=1), 95)),
    "kmeans_matches_nearest_original_centroid_ratio": float(np.mean(baseline_labels == nearest_original_centroid)),
}

metric_embeddings_baseline = article_embeddings_reduced
metric_labels_baseline = baseline_labels
if len(metric_labels_baseline) > QUALITY_SAMPLE_SIZE:
    rng = np.random.default_rng(42)
    sample_idx = rng.choice(len(metric_labels_baseline), size=QUALITY_SAMPLE_SIZE, replace=False)
    metric_embeddings_baseline = metric_embeddings_baseline[sample_idx]
    metric_labels_baseline = metric_labels_baseline[sample_idx]

baseline_quality["quality_sample_size"] = int(len(metric_labels_baseline))
metric_unique_labels_baseline = np.unique(metric_labels_baseline)
if 1 < len(metric_unique_labels_baseline) < len(metric_labels_baseline):
    baseline_quality["silhouette_cosine"] = float(silhouette_score(metric_embeddings_baseline, metric_labels_baseline, metric="cosine"))
    baseline_quality["davies_bouldin"] = float(davies_bouldin_score(metric_embeddings_baseline, metric_labels_baseline))
    baseline_quality["calinski_harabasz"] = float(calinski_harabasz_score(metric_embeddings_baseline, metric_labels_baseline))
else:
    baseline_quality["silhouette_cosine"] = np.nan
    baseline_quality["davies_bouldin"] = np.nan
    baseline_quality["calinski_harabasz"] = np.nan

baseline_quality_df = pd.DataFrame([baseline_quality])
BASELINE_CLUSTERING_QUALITY_CSV = ARTIFACTS / "articles_with_baseline_kmeans_quality.csv"
baseline_quality_df.to_csv(BASELINE_CLUSTERING_QUALITY_CSV, index=False)
print("Baseline quality saved:", BASELINE_CLUSTERING_QUALITY_CSV)
baseline_quality_df

Baseline quality saved: ..\data\artifacts\articles_with_baseline_kmeans_quality.csv

,n_articles,n_centroids,n_used_clusters,n_empty_clusters,mean_assigned_cosine_distance,median_assigned_cosine_distance,p95_assigned_cosine_distance,kmeans_matches_nearest_original_centroid_ratio,quality_sample_size,silhouette_cosine,davies_bouldin,calinski_harabasz
0,124282,333,333,0,0.08371,0.072332,0.186811,0.010162,10000,0.120719,1.758095,159.24266

## Comparison: ILC fixed centroids vs Standard KMeans baseline

In [29]:

comparison_df = pd.concat([
    quality_df.assign(method="ILC fixed centroids"),
    baseline_quality_df.assign(method="Standard KMeans"),
], ignore_index=True)

comparison_df = comparison_df[["method"] + [col for col in comparison_df.columns if col != "method"]]
print("Comparison of clustering methods:")
print(comparison_df.T)

COMPARISON_CSV = ARTIFACTS / "ilc_level2_kmeans_comparison.csv"
comparison_df.to_csv(COMPARISON_CSV, index=False)
print("\nComparison saved:", COMPARISON_CSV)
comparison_df

Comparison of clustering methods:
                                                                  0  \
method                                          ILC fixed centroids
n_articles                                                   124282
n_centroids                                                     333
n_used_clusters                                                 333
n_empty_clusters                                                  0
mean_assigned_cosine_distance                              0.272159
median_assigned_cosine_distance                            0.230579
p95_assigned_cosine_distance                               0.612932
kmeans_matches_nearest_original_centroid_ratio             0.521789
quality_sample_size                                           10000
silhouette_cosine                                          0.052949
davies_bouldin                                             1.836095
calinski_harabasz                                        115.364325

                                                              1
method                                          Standard KMeans
n_articles                                               124282
n_centroids                                                 333
n_used_clusters                                             333
n_empty_clusters                                              0
mean_assigned_cosine_distance                           0.08371
median_assigned_cosine_distance                        0.072332
p95_assigned_cosine_distance                           0.186811
kmeans_matches_nearest_original_centroid_ratio         0.010162
quality_sample_size                                       10000
silhouette_cosine                                      0.120719
davies_bouldin                                         1.758095
calinski_harabasz                                     159.24266

Comparison saved: ..\data\artifacts\ilc_level2_kmeans_comparison.csv

,method,n_articles,n_centroids,n_used_clusters,n_empty_clusters,mean_assigned_cosine_distance,median_assigned_cosine_distance,p95_assigned_cosine_distance,kmeans_matches_nearest_original_centroid_ratio,quality_sample_size,silhouette_cosine,davies_bouldin,calinski_harabasz
0,ILC fixed centroids,124282,333,333,0,0.272159,0.230579,0.612932,0.521789,10000,0.052949,1.836095,115.364325
1,Standard KMeans,124282,333,333,0,0.083710,0.072332,0.186811,0.010162,10000,0.120719,1.758095,159.242660

## Level 1 ILC Analysis: Clustering Level 2 centroids by Level 1 groups

This section analyzes the ILC hierarchy by grouping Level 2 centroids under their Level 1 parents and performing intra-group analysis of clusters.

In [30]:

# Collect Level 1 centroids
level1_nodes = []
for root in ilc_tree:
    level1_nodes.append(root)

def build_level1_text(node):
    parts = [node.get("description", ""), node.get("label", "")]
    return " ".join(str(part).strip() for part in parts if str(part).strip())

df_centroids_level1 = pd.DataFrame([
    {
        "notation": node.get("notation"),
        "label": node.get("label"),
        "combined_text": build_level1_text(node),
    }
    for node in level1_nodes
])

print("ILC level 1 centroids:", len(df_centroids_level1))
df_centroids_level1.head()

ILC level 1 centroids: 65

  notation            label    combined_text
0        ~         infinity         infinity
1        *         absolute         absolute
2        A            those            those
3        B   the first ones   the first ones
4        C  the second ones  the second ones

In [31]:

# Group Level 2 centroids by their Level 1 parents
level2_to_level1 = {}
for root in ilc_tree:
    level1_notation = root.get("notation")
    for child in root.get("children", []):
        level2_notation = child.get("notation")
        level2_to_level1[level2_notation] = level1_notation

df_centroids["level1_notation"] = df_centroids["notation"].map(level2_to_level1)
df_centroids["level1_label"] = df_centroids["level1_notation"].map(
    lambda x: df_centroids_level1[df_centroids_level1["notation"] == x]["label"].iloc[0] if x else None
)

print("Level 2 centroids grouped by Level 1:")
df_centroids.groupby("level1_label").size().sort_values(ascending=False)

Level 2 centroids grouped by Level 1:

level1_label
rituals                  28
molecules                26
artworks                 23
artifacts                18
forms                    18
technologies             18
land                     16
celestial bodies         15
continuum bodies         15
rocks                    14
language                 13
organisms                13
consciousness            11
populations              11
knowledge                10
energy                   10
atoms                    10
communities              10
instincts                 9
polities                  9
enterprises               8
genes                     7
spacetime                 5
branes                    4
the following             4
something                 4
bacteria                  3
persons by birth time     1
dtype: int64

In [32]:

# Analyze clusters within each Level 1 group
for level1_notation, level1_group in df_centroids.groupby("level1_notation"):
    level1_label = level1_group["level1_label"].iloc[0]
    print(f"\n=== Level 1: {level1_label} ({level1_notation}) ===")
    print(f"Number of Level 2 centroids: {len(level1_group)}")

    # Get articles assigned to these Level 2 clusters
    level2_notations = level1_group["notation"].tolist()
    group_articles = df_result[df_result["ilc_notation"].isin(level2_notations)]

    print(f"Total articles in this Level 1 group: {len(group_articles)}")

    # Summary by Level 2 clusters within this group
    cluster_summary = group_articles.groupby(["ilc_notation", "ilc_label"]).size().reset_index(name="articles_count")
    cluster_summary = cluster_summary.sort_values("articles_count", ascending=False)
    print("Level 2 clusters within this group:")
    for _, row in cluster_summary.iterrows():
        print(f"  {row['ilc_notation']}: {row['ilc_label']} - {row['articles_count']} articles")

=== Level 1: persons by birth time (U) ===
Number of Level 2 centroids: 1
Total articles in this Level 1 group: 15
Level 2 clusters within this group:
  UX: persons by birth millennium - 15 articles

=== Level 1: something (X) ===
Number of Level 2 centroids: 4
Total articles in this Level 1 group: 903
Level 2 clusters within this group:
  XB: x1 - 527 articles
  XC: x2 - 135 articles
  XA: x0 - 134 articles
  XX: what - 107 articles

=== Level 1: the following (Z) ===
Number of Level 2 centroids: 4
Total articles in this Level 1 group: 449
Level 2 clusters within this group:
  ZA: the aforementioned - 195 articles
  ZD: the third next - 142 articles
  ZC: the second next - 73 articles
  ZB: the next following - 39 articles

=== Level 1: forms (a) ===
Number of Level 2 centroids: 18
Total articles in this Level 1 group: 7123
Level 2 clusters within this group:
  at: algorithms - 2122 articles
  am: combinatorial structures - 823 articles
  aw: systems - 805 articles
  al: algebraic structures - 488 articles
  an: quantities - 475 articles
  aj: formal languages - 461 articles
  au: probabilities - 454 articles
  aiWj: discrete structures - 383 articles
  ag: operations - 363 articles
  aq: functions - 181 articles
  aWz: world - 111 articles
  ai: statements - 105 articles
  ab: individuals - 95 articles
  ae: relations - 75 articles
  af: predications - 62 articles
  ac: classes - 55 articles
  aa: attributes of #aa - 37 articles
  ak: spaces - 28 articles

=== Level 1: spacetime (b) ===
Number of Level 2 centroids: 5
Total articles in this Level 1 group: 1443
Level 2 clusters within this group:
  bv: motion - 612 articles
  bp: processes - 514 articles
  bb: time - 257 articles
  bY: present - 31 articles
  bc: space - 29 articles

=== Level 1: branes (c) ===
Number of Level 2 centroids: 4
Total articles in this Level 1 group: 2945
Level 2 clusters within this group:
  cd: membranes - 1548 articles
  cX: dimensionality - 756 articles
  cb: pointlike branes - 501 articles
  cc: strings - 140 articles

=== Level 1: energy (d) ===
Number of Level 2 centroids: 10
Total articles in this Level 1 group: 4429
Level 2 clusters within this group:
  dh: Higgs bosons - 861 articles
  dt: leptons - 729 articles
  dd: quantum fields - 590 articles
  dqWt: elementary fermions - 505 articles
  dv: hadrons - 439 articles
  dg: gauge bosons - 424 articles
  di: gravitons - 406 articles
  dgWi: elementary bosons - 367 articles
  dq: quarks - 63 articles
  da: attributes of #da - 45 articles

=== Level 1: atoms (e) ===
Number of Level 2 centroids: 10
Total articles in this Level 1 group: 3442
Level 2 clusters within this group:
  eb: period 1 elements - 997 articles
  eU: metals - 729 articles
  ec: period 2 elements - 643 articles
  eh: period 7 elements - 338 articles
  eg: period 6 elements - 287 articles
  ee: period 4 elements - 154 articles
  ed: period 3 elements - 145 articles
  ea: attributes of #ea - 88 articles
  ef: period 5 elements - 37 articles
  eX: periods - 24 articles

=== Level 1: molecules (f) ===
Number of Level 2 centroids: 26
Total articles in this Level 1 group: 14321
Level 2 clusters within this group:
  fp: lipids - 2415 articles
  fx: solid state compounds - 2288 articles
  fc: mineral acids - 1326 articles
  fl: carboxylic acids - 1062 articles
  fgzt: transition metal compounds - 1026 articles
  fu: nucleic acids - 945 articles
  fd: bases - 724 articles
  fe: oxides - 593 articles
  fk: ketones - 590 articles
  fh: hydrocarbons - 543 articles
  ft: proteins - 467 articles
  fcWe: inorganic compounds - 445 articles
  fq: nucleotides - 303 articles
  fj: aldehydes - 264 articles
  fm: esters - 197 articles
  fcWy: chemical compounds - 197 articles
  fhWu: organic compounds - 150 articles
  fi: alcohols - 147 articles
  fU: water - 142 articles
  fkze: ethers - 130 articles
  fn: amines - 105 articles
  ff: salts - 95 articles
  fg: complexes - 50 articles
  fo: carbohydrates - 49 articles
  fa: attributes of #fa - 36 articles
  fb: pure substances - 32 articles

=== Level 1: continuum bodies (g) ===
Number of Level 2 centroids: 15
Total articles in this Level 1 group: 11616
Level 2 clusters within this group:
  gs: solids - 1911 articles
  ggWl: fluids - 1895 articles
  gy: Bose-Einstein condensates - 1802 articles
  ge: quark-gluon plasma - 1489 articles
  gg: gases - 1181 articles
  gm: superfluids - 1040 articles
  gf: plasma - 914 articles
  gi: dispersions - 528 articles
  gx: crystals - 226 articles
  go: gels - 173 articles
  gr: supersolids - 152 articles
  gq: glasses - 146 articles
  gd: degenerate matter - 92 articles
  ga: attributes of #ga - 36 articles
  gl: liquids - 31 articles

=== Level 1: celestial bodies (h) ===
Number of Level 2 centroids: 15
Total articles in this Level 1 group: 6385
Level 2 clusters within this group:
  hb: nebulae - 1317 articles
  hs: planetary satellites - 1265 articles
  ht: planetary systems - 1010 articles
  hq: minor planets - 798 articles
  hu: star clusters - 638 articles
  hr: meteoroids - 611 articles
  hc: clouds - 219 articles
  hU: the Earth - 121 articles
  hl: stars - 92 articles
  hp: planets - 72 articles
  hg: galaxies - 66 articles
  hh: galaxy associations - 53 articles
  ha: attributes of #ha - 49 articles
  hbzd: dark matter - 49 articles
  hk: brown dwarves - 25 articles

=== Level 1: rocks (i) ===
Number of Level 2 centroids: 14
Total articles in this Level 1 group: 3144
Level 2 clusters within this group:
  ik: rock beds - 647 articles
  it: tectonic plates - 446 articles
  ig: magma - 428 articles
  ikWp: rock units - 363 articles
  is: crust structural zones - 341 articles
  im: rock formations - 210 articles
  ip: rock groups - 148 articles
  io: rock subgroups - 140 articles
  ib: minerals - 118 articles
  iq: rock supergroups - 112 articles
  ii: single rocks - 99 articles
  id: mineraloids - 67 articles
  il: rock members - 18 articles
  ia: attributes of #ia - 7 articles

=== Level 1: land (j) ===
Number of Level 2 centroids: 16
Total articles in this Level 1 group: 5572
Level 2 clusters within this group:
  jr: glaciers - 1494 articles
  js: fresh water systems - 1019 articles
  jl: plains - 669 articles
  jqWy: water reservoirs - 575 articles
  jq: aquifers - 453 articles
  jU: regions of the contemporary Earth - 225 articles
  jo: soils - 206 articles
  jb: morphological elements - 146 articles
  jf: stone runs - 132 articles
  jw: islands - 131 articles
  jv: shores - 126 articles
  jy: seas - 116 articles
  jj: valleys - 113 articles
  jx: archipelagos - 84 articles
  jd: mountains - 66 articles
  ja: attributes of #ja - 17 articles

=== Level 1: genes (k) ===
Number of Level 2 centroids: 7
Total articles in this Level 1 group: 3619
Level 2 clusters within this group:
  ki: plasmids - 1782 articles
  ke: mRNA - 1102 articles
  kv: viruses - 243 articles
  km: genomes - 201 articles
  kf: tRNA - 162 articles
  kh: chromosomes - 111 articles
  ka: attributes of #ka - 18 articles

=== Level 1: bacteria (l) ===
Number of Level 2 centroids: 3
Total articles in this Level 1 group: 218
Level 2 clusters within this group:
  lk: eubacteria - 101 articles
  lh: archaea - 85 articles
  la: attributes of #la - 32 articles

=== Level 1: organisms (m) ===
Number of Level 2 centroids: 13
Total articles in this Level 1 group: 2173
Level 2 clusters within this group:
  mh: chromalveolata - 654 articles
  mo: red algae - 586 articles
  mY: individuals - 308 articles
  mU: human organisms - 148 articles
  me: excavates - 133 articles
  mj: amoebozoa - 67 articles
  mn: fungi - 53 articles
  mp: plants - 49 articles
  mg: rhizaria - 49 articles
  ma: attributes of #ma - 45 articles
  mq: animals - 31 articles
  mX: kingdoms - 27 articles
  meWl: protists - 23 articles

=== Level 1: populations (n) ===
Number of Level 2 centroids: 11
Total articles in this Level 1 group: 3128
Level 2 clusters within this group:
  nb: aggregation groups - 1013 articles
  nu: biocoenoses - 623 articles
  nt: trophic systems - 366 articles
  ns: biological associations - 241 articles
  nm: populations - 199 articles
  np: phylogenetic lineages - 192 articles
  ne: colonies - 147 articles
  nbWm: intraspecific relations - 130 articles
  ny: ecosystems - 126 articles
  na: attributes of #na - 60 articles
  nrWy: interspecific relations - 31 articles

=== Level 1: instincts (o) ===
Number of Level 2 centroids: 9
Total articles in this Level 1 group: 6098
Level 2 clusters within this group:
  oc: autonomous activities - 1380 articles
  op: fixed action patterns - 1274 articles
  os: behavioural sequences - 1091 articles
  om: locomotion - 906 articles
  ok: taxes and tropisms - 535 articles
  of: reflexes - 432 articles
  oh: hereditary coordinations - 324 articles
  oa: attributes of #oa - 102 articles
  oy: life habits - 54 articles

=== Level 1: consciousness (p) ===
Number of Level 2 centroids: 11
Total articles in this Level 1 group: 2410
Level 2 clusters within this group:
  pc: perception - 694 articles
  po: cognition - 344 articles
  ps: self - 299 articles
  pj: unconscious mind - 274 articles
  pY: actual persons - 229 articles
  pl: awareness - 191 articles
  pe: emotions - 112 articles
  pa: attributes of #pa - 104 articles
  ph: personality - 74 articles
  pg: moods - 52 articles
  px: persons - 37 articles

=== Level 1: language (q) ===
Number of Level 2 centroids: 13
Total articles in this Level 1 group: 5464
Level 2 clusters within this group:
  qw: language transmission systems - 2222 articles
  qg: combined sounds - 978 articles
  qq: clauses - 534 articles
  qs: sentences - 266 articles
  qv: languages - 262 articles
  qh: syllables - 228 articles
  qa: attributes of #qa - 204 articles
  qt: texts - 203 articles
  qm: morphs - 139 articles
  qo: words - 132 articles
  qe: phones - 130 articles
  qf: phonemes - 115 articles
  qp: phrases - 51 articles

=== Level 1: rituals (r) ===
Number of Level 2 centroids: 28
Total articles in this Level 1 group: 3011
Level 2 clusters within this group:
  rf: Jainism - 713 articles
  ra: attributes of #ra - 682 articles
  rvzo: Cao Dai - 176 articles
  rd: Hinduism - 149 articles
  rw: New Age - 120 articles
  rwzs: Scientology - 99 articles
  rk: Confucianism - 97 articles
  rvzf: Anthroposophy - 95 articles
  rX: faiths - 91 articles
  rg: Sikhism - 74 articles
  rx: Theosophy - 74 articles
  re: Carvaka - 71 articles
  rr: Zoroastrianism - 71 articles
  rt: Christianity - 65 articles
  ru: Islam - 59 articles
  rl: Legalism - 46 articles
  rv: Bahá'í faith - 44 articles
  rp: ancient Egyptian religion - 43 articles
  rs: Judaism - 42 articles
  rn: Taoism - 38 articles
  rsWu: Abrahamic religions - 30 articles
  rvzr: Rastafarianism - 27 articles
  rh: Buddhism - 26 articles
  rq: paganism - 24 articles
  rc: Vedic Brahmanism - 21 articles
  ry: Humanism - 18 articles
  ro: Shinto - 10 articles
  rm: Mohism - 6 articles

=== Level 1: communities (s) ===
Number of Level 2 centroids: 10
Total articles in this Level 1 group: 1802
Level 2 clusters within this group:
  sa: attributes of #sa - 542 articles
  sp: public institutions - 328 articles
  so: organized civil society - 309 articles
  sb: citizens - 189 articles
  sj: castes - 118 articles
  st: peoples - 102 articles
  sg: clans - 76 articles
  sy: civilizations - 68 articles
  sf: families - 38 articles
  sl: classes - 32 articles

=== Level 1: polities (t) ===
Number of Level 2 centroids: 9
Total articles in this Level 1 group: 1179
Level 2 clusters within this group:
  tk: city-states - 360 articles
  tw: intergovernmental organizations - 308 articles
  tt: modern nation states - 151 articles
  tu: supranational unions - 124 articles
  th: chiefdoms - 55 articles
  tb: bands - 53 articles
  tp: empires - 52 articles
  te: tribes - 49 articles
  ta: attributes of #ta - 27 articles

=== Level 1: enterprises (u) ===
Number of Level 2 centroids: 8
Total articles in this Level 1 group: 6539
Level 2 clusters within this group:
  uo: corporations - 2039 articles
  ul: limited liability companies - 1531 articles
  uj: cooperative businesses - 1150 articles
  uy: economies - 815 articles
  uq: financial institutions - 471 articles
  ua: attributes of #ua - 224 articles
  ub: public - 180 articles
  ud: private - 129 articles

=== Level 1: technologies (v) ===
Number of Level 2 centroids: 18
Total articles in this Level 1 group: 7612
Level 2 clusters within this group:
  vt: manufacturing - 2277 articles
  vbWk: primary sector - 1136 articles
  vx: transport - 821 articles
  vs: construction - 739 articles
  vc: fishing - 498 articles
  va: attributes of #va - 288 articles
  vf: forestry - 280 articles
  vk: animal husbandry - 229 articles
  vm: health care - 227 articles
  vd: mining - 227 articles
  vr: crafts - 194 articles
  vj: aquaculture - 143 articles
  vi: farming - 138 articles
  vh: horticulture - 104 articles
  vn: mental health care - 88 articles
  vq: cooking - 88 articles
  vb: foraging - 75 articles
  ve: conservation - 60 articles

=== Level 1: artifacts (w) ===
Number of Level 2 centroids: 18
Total articles in this Level 1 group: 12035
Level 2 clusters within this group:
  ww: settlements - 2268 articles
  ws: buildings - 1996 articles
  wh: cleaning tools - 1775 articles
  wo: measuring and alignment tools - 1300 articles
  wv: vehicles - 846 articles
  wu: utilities - 744 articles
  wm: musical instruments - 734 articles
  wn: information devices - 700 articles
  wj: agricultural tools - 416 articles
  wr: furnishings - 408 articles
  wd: pharmaceutical drugs - 353 articles
  we: medical equipments - 276 articles
  wk: weapons - 55 articles
  wa: attributes of #wa - 55 articles
  wf: clothing - 51 articles
  wg: personal adornment - 39 articles
  wb: dishes - 10 articles
  wi: pots - 9 articles

=== Level 1: artworks (x) ===
Number of Level 2 centroids: 23
Total articles in this Level 1 group: 4196
Level 2 clusters within this group:
  xbWd: plastic arts - 499 articles
  xb: sculptures - 484 articles
  xbWh: cultural property - 446 articles
  xeWi: visual arts - 294 articles
  xY: work entitled - 286 articles
  xs: films - 284 articles
  xg: drawings - 259 articles
  xe: mosaics - 237 articles
  xc: engravements - 204 articles
  xi: calligraphy - 180 articles
  xr: theatre - 139 articles
  xh: photographic art - 116 articles
  xl: literature - 107 articles
  xv: martial arts - 105 articles
  xmWr: performing arts - 102 articles
  xy: entertainment - 99 articles
  xm: music - 94 articles
  xo: circus - 81 articles
  xd: art ceramics - 68 articles
  xf: paintings - 50 articles
  xa: attributes of #xa - 37 articles
  xw: sport - 22 articles
  xn: dance - 3 articles

=== Level 1: knowledge (y) ===
Number of Level 2 centroids: 10
Total articles in this Level 1 group: 3011
Level 2 clusters within this group:
  yx: knowledge organization systems - 1227 articles
  yv: document collections - 568 articles
  yo: congresses - 323 articles
  yt: documents - 282 articles
  yi: disciplines - 153 articles
  yc: concepts - 151 articles
  ye: theories - 123 articles
  ya: attributes of #ya - 93 articles
  yl: schools - 54 articles
  ym: academies - 37 articles

In [33]:

# Function to compute log-odds ratio for words in a cluster vs overall corpus
def compute_log_odds_ratio(cluster_texts, corpus_texts, top_n=50):
    """
    Compute log-odds ratio for words in cluster vs overall corpus.
    Returns top_n words with highest log-odds ratio.
    """
    from collections import Counter
    import re
    import numpy as np
    # Tokenize and count words in cluster
    cluster_words = []
    for text in cluster_texts:
        words = re.findall(r'\b\w+\b', text.lower())
        cluster_words.extend(words)

    cluster_counts = Counter(cluster_words)
    cluster_total = len(cluster_words)

    # Tokenize and count words in corpus
    corpus_words = []
    for text in corpus_texts:
        words = re.findall(r'\b\w+\b', text.lower())
        corpus_words.extend(words)

    corpus_counts = Counter(corpus_words)
    corpus_total = len(corpus_words)

    # Compute log-odds ratio
    log_odds = {}
    for word in set(cluster_words + corpus_words):
        if word not in cluster_counts:
            cluster_counts[word] = 0
        if word not in corpus_counts:
            corpus_counts[word] = 0

        # Add smoothing
        cluster_freq = (cluster_counts[word] + 1) / (cluster_total + len(corpus_counts))
        corpus_freq = (corpus_counts[word] + 1) / (corpus_total + len(corpus_counts))

        odds_ratio = cluster_freq / corpus_freq
        log_odds[word] = np.log(odds_ratio)

    # Return top_n words with highest log-odds
    sorted_words = sorted(log_odds.items(), key=lambda x: x[1], reverse=True)
    return dict(sorted_words[:top_n])

# Create results_odds directory
RESULTS_ODDS_DIR = ARTIFACTS / "results_odds"
RESULTS_ODDS_DIR.mkdir(parents=True, exist_ok=True)

# Function to generate word cloud from log-odds
def generate_wordcloud(log_odds_dict, title="Word Cloud", filename=None):
    from wordcloud import WordCloud
    import matplotlib.pyplot as plt
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate_from_frequencies(log_odds_dict)

    # Save to file only, do not display
    if filename:
        # Use matplotlib to save without displaying
        fig, ax = plt.subplots(figsize=(10, 5))
        ax.imshow(wordcloud, interpolation='bilinear')
        ax.axis('off')
        ax.set_title(title)
        plt.savefig(filename, bbox_inches='tight', dpi=150)
        plt.close(fig)
        print(f"Saved word cloud to: {filename}")
    else:

        print(f"No filename provided for: {title}")

In [34]:
import re

In [35]:

# Compute log-odds ratio and generate word clouds for each Level 2 cluster
corpus_texts = df_articles["smart_features"].fillna("").tolist()

for level1_notation, level1_group in df_centroids.groupby("level1_notation"):
    level1_label = level1_group["level1_label"].iloc[0]
    print(f"\n=== Generating word clouds for Level 1: {level1_label} ===")

    for _, level2_row in level1_group.iterrows():
        level2_notation = level2_row["notation"]
        level2_label = level2_row["label"]

        # Get articles in this Level 2 cluster
        cluster_articles = df_result[df_result["ilc_notation"] == level2_notation]
        cluster_texts = cluster_articles["smart_features"].fillna("").tolist()

        if len(cluster_texts) < 10:  # Skip clusters with too few articles
            print(f"Skipping {level2_notation}: {level2_label} - only {len(cluster_texts)} articles")
            continue

        print(f"Processing {level2_notation}: {level2_label} - {len(cluster_texts)} articles")

        # Compute log-odds ratio
        log_odds = compute_log_odds_ratio(cluster_texts, corpus_texts, top_n=50)

        # Generate word cloud and save to file
        title = f"Level 2: {level2_label} ({level2_notation})\n{len(cluster_texts)} articles"
        filename = RESULTS_ODDS_DIR / f"wordcloud_{level1_notation}_{level2_notation}.png"
        generate_wordcloud(log_odds, title=title, filename=str(filename))

=== Generating word clouds for Level 1: persons by birth time ===
Processing UX: persons by birth millennium - 15 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_U_UX.png

=== Generating word clouds for Level 1: something ===
Processing XA: x0 - 134 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_X_XA.png
Processing XB: x1 - 527 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_X_XB.png
Processing XC: x2 - 135 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_X_XC.png
Processing XX: what - 107 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_X_XX.png

=== Generating word clouds for Level 1: the following ===
Processing ZA: the aforementioned - 195 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_Z_ZA.png
Processing ZB: the next following - 39 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_Z_ZB.png
Processing ZC: the second next - 73 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_Z_ZC.png
Processing ZD: the third next - 142 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_Z_ZD.png

=== Generating word clouds for Level 1: forms ===
Processing aWz: world - 111 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_aWz.png
Processing aa: attributes of #aa - 37 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_aa.png
Processing ab: individuals - 95 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_ab.png
Processing ac: classes - 55 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_ac.png
Processing ae: relations - 75 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_ae.png
Processing af: predications - 62 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_af.png
Processing ag: operations - 363 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_ag.png
Processing ai: statements - 105 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_ai.png
Processing aiWj: discrete structures - 383 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_aiWj.png
Processing aj: formal languages - 461 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_aj.png
Processing ak: spaces - 28 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_ak.png
Processing al: algebraic structures - 488 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_al.png
Processing am: combinatorial structures - 823 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_am.png
Processing an: quantities - 475 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_an.png
Processing aq: functions - 181 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_aq.png
Processing at: algorithms - 2122 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_at.png
Processing au: probabilities - 454 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_au.png
Processing aw: systems - 805 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_a_aw.png

=== Generating word clouds for Level 1: spacetime ===
Processing bY: present - 31 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_b_bY.png
Processing bb: time - 257 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_b_bb.png
Processing bc: space - 29 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_b_bc.png
Processing bp: processes - 514 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_b_bp.png
Processing bv: motion - 612 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_b_bv.png

=== Generating word clouds for Level 1: branes ===
Processing cX: dimensionality - 756 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_c_cX.png
Processing cb: pointlike branes - 501 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_c_cb.png
Processing cc: strings - 140 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_c_cc.png
Processing cd: membranes - 1548 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_c_cd.png

=== Generating word clouds for Level 1: energy ===
Processing da: attributes of #da - 45 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_d_da.png
Processing dd: quantum fields - 590 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_d_dd.png
Processing dg: gauge bosons - 424 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_d_dg.png
Processing dgWi: elementary bosons - 367 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_d_dgWi.png
Processing dh: Higgs bosons - 861 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_d_dh.png
Processing di: gravitons - 406 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_d_di.png
Processing dq: quarks - 63 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_d_dq.png
Processing dqWt: elementary fermions - 505 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_d_dqWt.png
Processing dt: leptons - 729 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_d_dt.png
Processing dv: hadrons - 439 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_d_dv.png

=== Generating word clouds for Level 1: atoms ===
Processing eU: metals - 729 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_e_eU.png
Processing eX: periods - 24 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_e_eX.png
Processing ea: attributes of #ea - 88 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_e_ea.png
Processing eb: period 1 elements - 997 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_e_eb.png
Processing ec: period 2 elements - 643 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_e_ec.png
Processing ed: period 3 elements - 145 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_e_ed.png
Processing ee: period 4 elements - 154 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_e_ee.png
Processing ef: period 5 elements - 37 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_e_ef.png
Processing eg: period 6 elements - 287 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_e_eg.png
Processing eh: period 7 elements - 338 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_e_eh.png

=== Generating word clouds for Level 1: molecules ===
Processing fU: water - 142 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fU.png
Processing fa: attributes of #fa - 36 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fa.png
Processing fb: pure substances - 32 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fb.png
Processing fc: mineral acids - 1326 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fc.png
Processing fcWe: inorganic compounds - 445 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fcWe.png
Processing fcWy: chemical compounds - 197 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fcWy.png
Processing fd: bases - 724 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fd.png
Processing fe: oxides - 593 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fe.png
Processing ff: salts - 95 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_ff.png
Processing fg: complexes - 50 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fg.png
Processing fgzt: transition metal compounds - 1026 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fgzt.png
Processing fh: hydrocarbons - 543 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fh.png
Processing fhWu: organic compounds - 150 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fhWu.png
Processing fi: alcohols - 147 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fi.png
Processing fj: aldehydes - 264 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fj.png
Processing fk: ketones - 590 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fk.png
Processing fkze: ethers - 130 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fkze.png
Processing fl: carboxylic acids - 1062 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fl.png
Processing fm: esters - 197 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fm.png
Processing fn: amines - 105 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fn.png
Processing fo: carbohydrates - 49 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fo.png
Processing fp: lipids - 2415 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fp.png
Processing fq: nucleotides - 303 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fq.png
Processing ft: proteins - 467 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_ft.png
Processing fu: nucleic acids - 945 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fu.png
Processing fx: solid state compounds - 2288 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_f_fx.png

=== Generating word clouds for Level 1: continuum bodies ===
Processing ga: attributes of #ga - 36 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_g_ga.png
Processing gd: degenerate matter - 92 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_g_gd.png
Processing ge: quark-gluon plasma - 1489 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_g_ge.png
Processing gf: plasma - 914 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_g_gf.png
Processing gg: gases - 1181 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_g_gg.png
Processing ggWl: fluids - 1895 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_g_ggWl.png
Processing gi: dispersions - 528 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_g_gi.png
Processing gl: liquids - 31 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_g_gl.png
Processing gm: superfluids - 1040 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_g_gm.png
Processing go: gels - 173 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_g_go.png
Processing gq: glasses - 146 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_g_gq.png
Processing gr: supersolids - 152 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_g_gr.png
Processing gs: solids - 1911 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_g_gs.png
Processing gx: crystals - 226 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_g_gx.png
Processing gy: Bose-Einstein condensates - 1802 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_g_gy.png

=== Generating word clouds for Level 1: celestial bodies ===
Processing hU: the Earth - 121 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_h_hU.png
Processing ha: attributes of #ha - 49 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_h_ha.png
Processing hb: nebulae - 1317 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_h_hb.png
Processing hbzd: dark matter - 49 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_h_hbzd.png
Processing hc: clouds - 219 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_h_hc.png
Processing hg: galaxies - 66 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_h_hg.png
Processing hh: galaxy associations - 53 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_h_hh.png
Processing hk: brown dwarves - 25 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_h_hk.png
Processing hl: stars - 92 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_h_hl.png
Processing hp: planets - 72 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_h_hp.png
Processing hq: minor planets - 798 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_h_hq.png
Processing hr: meteoroids - 611 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_h_hr.png
Processing hs: planetary satellites - 1265 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_h_hs.png
Processing ht: planetary systems - 1010 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_h_ht.png
Processing hu: star clusters - 638 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_h_hu.png

=== Generating word clouds for Level 1: rocks ===
Skipping ia: attributes of #ia - only 7 articles
Processing ib: minerals - 118 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_i_ib.png
Processing id: mineraloids - 67 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_i_id.png
Processing ig: magma - 428 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_i_ig.png
Processing ii: single rocks - 99 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_i_ii.png
Processing ik: rock beds - 647 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_i_ik.png
Processing ikWp: rock units - 363 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_i_ikWp.png
Processing il: rock members - 18 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_i_il.png
Processing im: rock formations - 210 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_i_im.png
Processing io: rock subgroups - 140 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_i_io.png
Processing ip: rock groups - 148 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_i_ip.png
Processing iq: rock supergroups - 112 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_i_iq.png
Processing is: crust structural zones - 341 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_i_is.png
Processing it: tectonic plates - 446 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_i_it.png

=== Generating word clouds for Level 1: land ===
Processing jU: regions of the contemporary Earth - 225 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_j_jU.png
Processing ja: attributes of #ja - 17 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_j_ja.png
Processing jb: morphological elements - 146 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_j_jb.png
Processing jd: mountains - 66 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_j_jd.png
Processing jf: stone runs - 132 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_j_jf.png
Processing jj: valleys - 113 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_j_jj.png
Processing jl: plains - 669 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_j_jl.png
Processing jo: soils - 206 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_j_jo.png
Processing jq: aquifers - 453 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_j_jq.png
Processing jqWy: water reservoirs - 575 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_j_jqWy.png
Processing jr: glaciers - 1494 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_j_jr.png
Processing js: fresh water systems - 1019 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_j_js.png
Processing jv: shores - 126 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_j_jv.png
Processing jw: islands - 131 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_j_jw.png
Processing jx: archipelagos - 84 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_j_jx.png
Processing jy: seas - 116 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_j_jy.png

=== Generating word clouds for Level 1: genes ===
Processing ka: attributes of #ka - 18 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_k_ka.png
Processing ke: mRNA - 1102 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_k_ke.png
Processing kf: tRNA - 162 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_k_kf.png
Processing kh: chromosomes - 111 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_k_kh.png
Processing ki: plasmids - 1782 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_k_ki.png
Processing km: genomes - 201 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_k_km.png
Processing kv: viruses - 243 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_k_kv.png

=== Generating word clouds for Level 1: bacteria ===
Processing la: attributes of #la - 32 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_l_la.png
Processing lh: archaea - 85 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_l_lh.png
Processing lk: eubacteria - 101 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_l_lk.png

=== Generating word clouds for Level 1: organisms ===
Processing mU: human organisms - 148 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_m_mU.png
Processing mX: kingdoms - 27 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_m_mX.png
Processing mY: individuals - 308 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_m_mY.png
Processing ma: attributes of #ma - 45 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_m_ma.png
Processing me: excavates - 133 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_m_me.png
Processing meWl: protists - 23 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_m_meWl.png
Processing mg: rhizaria - 49 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_m_mg.png
Processing mh: chromalveolata - 654 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_m_mh.png
Processing mj: amoebozoa - 67 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_m_mj.png
Processing mn: fungi - 53 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_m_mn.png
Processing mo: red algae - 586 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_m_mo.png
Processing mp: plants - 49 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_m_mp.png
Processing mq: animals - 31 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_m_mq.png

=== Generating word clouds for Level 1: populations ===
Processing na: attributes of #na - 60 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_n_na.png
Processing nb: aggregation groups - 1013 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_n_nb.png
Processing nbWm: intraspecific relations - 130 articles
Saved word cloud to: ..\data\artifacts\results_odds\wordcloud_n_nbWm.png